# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Trojmiasto JUG
tagline:          'Dev home in 3city'
description:      ''
url:              https://trojmiasto.jug.pl
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'JUG Trojmiasto'
  url:            https://meetup.com/Trojmiasto-Java-User-Group/

paginate:         10
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  profile: https://github.com/trojmiasto-jug

mail: jugtrojmiasto@gmail.com

meetup:
  profile: https://www.meetup.com/Trojmiasto-Java-User-Group/

youtube:
  profile: https://www.youtube.com/channel/UCU5x5RmlIUUTyZIQKZkXHUw/

facebook:
  profile: https://www.facebook.com/TrojmiastoJUG/

twitter:
  profile: https://twitter.com/JUGTricity
